const constants = {
  SET_TEACHERS: 'SET_TEACHERS',
  ADD_TEACHER: 'ADD_TEACHER',
  SET_LESSONS: 'SET_LESSONS',
  ADD_LESSON: 'ADD_LESSON',
  SET_STUDENTS_FOR_LESSON: 'SET_STUDENTS_FOR_LESSON',
  ADD_STUDENT_TO_LESSON: 'ADD_STUDENT_TO_LESSON'
};

export default constants;
